// Real logged-food names, snapshotted from app/qa_seed.py (the seeded QA personas), used as
// a resolver corpus by foodCategory.test.ts and scripts/auditCategories.ts. Refresh with:
//   grep -oE 'FoodTemplate\("[^"]+"' app/qa_seed.py | sed -E 's/FoodTemplate\("(.*)"/\1/' | sort -u
export const SEED_FOOD_NAMES: string[] = [
  'Apple with peanut butter',
  'Bagel breakfast sandwich',
  'Beef stir fry with rice',
  'Breakfast sandwich',
  'Caesar salad with chicken',
  'Chicken burrito bowl',
  'Chicken fajita plate',
  'Chicken pasta bake',
  'Chicken quinoa salad',
  'Coffee',
  'Coffee with milk',
  'Cottage cheese cup',
  'Egg white veggie scramble',
  'Eggs, toast, and potatoes',
  'Greek yogurt granola bowl',
  'Greek yogurt with berries',
  'Ice cream',
  'Mass-gainer oatmeal',
  'Pasta with turkey meat sauce',
  'Peanut butter banana smoothie',
  'Pizza slices',
  'Protein bar',
  'Protein oatmeal',
  'Restaurant burger and fries',
  'Salmon sweet potato plate',
  'Salmon, rice, and broccoli',
  'Steak rice plate',
  'Sushi lunch combo',
  'Takeout pad thai',
  'Trail mix',
  'Tuna rice bowl',
  'Turkey avocado wrap',
  'Turkey chili',
  'Whey protein shake',
  'Wine',
]
